name: news_summarizer
description: A client app for a news summarizer

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^3.0.9
  provider: ^4.1.3+1
  material_design_icons_flutter: 4.0.5345
  animations: ^1.1.1
  firebase_core: ^0.5.0
  firebase_analytics: ^6.0.0
  firebase_auth: ^0.18.0+1
  google_sign_in: ^4.5.1
  get: ^3.8.0
  pin_code_fields: ^4.0.0
  shared_preferences: ^0.5.10
  http: ^0.12.2
  cached_network_image: ^2.3.1
  html: ^0.14.0+3
  intl: ^0.16.1
  webview_flutter: ^0.3.22+1
  chips_choice: ^1.2.0
  hive: ^1.4.4
  hive_flutter: ^0.3.1
  path_provider: ^1.6.14

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator:
  build_runner:


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  fonts:
    - family: Circular-Std
      fonts:
        - asset: assets/fonts/CircularStd-Black.ttf
        - asset: assets/fonts/CircularStd-Bold.ttf
          weight: 700
        - asset: assets/fonts/CircularStd-Medium.ttf
          weight: 500
        - asset: assets/fonts/CircularStd-Book.ttf
          weight: 300
  assets:
    - assets/icons/